apiVersion: v1
kind: Pod
metadata:
  name: sec-test-passed
spec:
  containers:
    - name: sec-test-passed
      image: klaus1982/k82_priv_imgs
      imagePullPolicy: Always
  imagePullSecrets:
    - name: k82
