apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: web
  name: web-controller
spec:
  replicas: 1
  selector:
    name: web
  template:
    metadata:
      labels:
        name: web
    spec:
      containers:
      - image: klaus1982/web-demo-priv
        name: web
        imagePullPolicy: Always
        ports:
        - name: web
          containerPort: 3001
      imagePullSecrets:
        - name: k82
