apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: web
  name: web-controller
spec:
  replicas: 2
  selector:
    name: web
  template:
    metadata:
      labels:
        name: web
    spec:
      containers:
      - image: klaus1982/web-demo
        name: web
        ports:
        - name: nodejs
          containerPort: 3001
          hostPort: 3001
