apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    name: jenkins
  name: jenkins-controller
  namespace: default
spec:
  replicas: 1
  selector:
    name: jenkins
  template:
    metadata:
      labels:
        name: jenkins
    spec:
      containers:
      - image: jenkins
        name: jenkins
        ports:
        - name: jenkins
          containerPort: 8080
          hostPort: 31200
        volumeMounts :
        - name : jenkins-home
          mountPath : /var/jenkins_home
      volumes :
      - name : jenkins-home
        glusterfs :
          endpoints : glusterfs-cluster
          path : jenkins
          readOnly : false
