apiVersion: v1
kind: ReplicationController
metadata:
  labels:
    app: jenkins
  name: jenkins
  namespace: default
spec:
  replicas: 1
  selector:
    app: jenkins
  template:
    metadata:
      labels:
        app: jenkins
      name: jenkins
    spec:
      containers:
      - image: jenkins
        imagePullPolicy: Always
        name: jenkins
        volumeMounts :
        - name : jenkins-home
          mountPath : /var/jenkins_home
      volumes :
      - name : jenkins-home
        hostPath :
          path : /home/yfeng/jenkins_home/
