apiVersion: v1
kind: Service
metadata:
  labels:
    app: jenkins
  name: jenkins
  namespace: default
spec:
  ports:
  - port: 29080
    protocol: TCP
    targetPort: 8080
  selector:
    app: jenkins
  type: LoadBalancer
