apiVersion: v1
kind: Service
metadata:
  name: jenkins
  labels:
    name: jenkins
spec:
  type: LoadBalancer
  ports:
    - port: 29080
      targetPort: 8080
      protocol: TCP
  selector:
    name: jenkins
